name: we_yapping_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.2.0+3
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Work_Sans
      fonts:
        - asset: assets/fonts/Work_Sans/static/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Work_Sans/static/WorkSans-Bold.ttf
          weight: 700
